# Generated by Django 5.2.16 on 2026-08-04 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnesthesiaTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Ekip Adı')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperatingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='oda Adı')),
                ('specialty_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Özel Uzmanlık/Tipi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(max_length=100, verbose_name='Doktor Adı')),
                ('specialty', models.CharField(max_length=100, verbose_name='Uzmanlık Alanı')),
                ('off_day', models.CharField(blank=True, max_length=20, null=True, verbose_name='İzinli Gün')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('patient_name', models.CharField(max_length=100, verbose_name='Hasta Adı/Kodu')),
                ('operation_name', models.CharField(max_length=100, verbose_name='Operasyon Adı')),
                ('required_specialty', models.CharField(max_length=100, verbose_name='Gereken Uzmanlık')),
                ('duration_slot', models.PositiveIntegerField(verbose_name='Süre (30dk Slot Sayısı)')),
                ('priority', models.CharField(choices=[('CRITICAL', 'Kritik'), ('HIGH', 'Yüksek'), ('MEDIUM', 'Orta'), ('LOW', 'Düşük')], default='MEDIUM', max_length=10, verbose_name='Öncelik')),
                ('required_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.operatingroom', verbose_name='Zorunlu Ameliyathane')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
