# Generated by Django 5.2.16 on 2026-08-04 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anesthesiateam',
            options={'ordering': ['name'], 'verbose_name': 'Anestezi Ekibi', 'verbose_name_plural': 'Anestezi Ekipleri'},
        ),
        migrations.AlterModelOptions(
            name='operatingroom',
            options={'ordering': ['name'], 'verbose_name': 'Ameliyathane / Oda', 'verbose_name_plural': 'Ameliyathaneler / Odalar'},
        ),
        migrations.AlterModelOptions(
            name='patientoperation',
            options={'verbose_name': 'Hasta Ameliyat Operasyonu', 'verbose_name_plural': 'Hasta Ameliyat Operasyonları'},
        ),
        migrations.AlterModelOptions(
            name='surgeon',
            options={'verbose_name': 'Cerrah', 'verbose_name_plural': 'Cerrahlar'},
        ),
        migrations.AddField(
            model_name='patientoperation',
            name='anesthesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.anesthesiateam', verbose_name='Atanan Anestezi'),
        ),
        migrations.AddField(
            model_name='patientoperation',
            name='surgeon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.surgeon', verbose_name='Atanan Cerrah'),
        ),
        migrations.AlterField(
            model_name='operatingroom',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Oda Adı'),
        ),
        migrations.AlterField(
            model_name='operatingroom',
            name='specialty_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Özel Uzmanlık / Tipi'),
        ),
        migrations.AlterField(
            model_name='patientoperation',
            name='duration_slot',
            field=models.PositiveIntegerField(default=1, help_text='Örn: 1 slot = 30 dk, 2 slot = 60 dk', verbose_name='Süre (30dk Slot Sayısı)'),
        ),
        migrations.AlterField(
            model_name='surgeon',
            name='off_day',
            field=models.CharField(blank=True, choices=[('monday', 'Pazartesi'), ('tuesday', 'Salı'), ('wednesday', 'Çarşamba'), ('thursday', 'Perşembe'), ('friday', 'Cuma'), ('saturday', 'Cumartesi'), ('sunday', 'Pazar')], max_length=20, null=True, verbose_name='İzinli Gün'),
        ),
    ]
