# Generated by Django 5.2.16 on 2026-08-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(max_length=100, verbose_name='Doktor Adı')),
                ('specialty', models.CharField(max_length=100, verbose_name='Uzmanlık Alanı')),
                ('off_day', models.CharField(blank=True, choices=[('monday', 'Pazartesi'), ('tuesday', 'Salı'), ('wednesday', 'Çarşamba'), ('thursday', 'Perşembe'), ('friday', 'Cuma'), ('saturday', 'Cumartesi'), ('sunday', 'Pazar')], max_length=20, null=True, verbose_name='İzinli Gün')),
            ],
            options={
                'verbose_name': 'Cerrah',
                'verbose_name_plural': 'Cerrahlar',
            },
        ),
    ]
