# Generated by Django 5.2.16 on 2026-08-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Oda Adı')),
                ('specialty_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Özel Uzmanlık / Tipi')),
            ],
            options={
                'verbose_name': 'Ameliyathane / Oda',
                'verbose_name_plural': 'Ameliyathaneler / Odalar',
                'ordering': ['name'],
            },
        ),
    ]
