# Generated by Django 5.2.16 on 2026-08-06 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anesthesia', '0001_initial'),
        ('room', '0001_initial'),
        ('surgeon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('patient_name', models.CharField(max_length=100, verbose_name='Hasta Adı/Kodu')),
                ('operation_name', models.CharField(max_length=100, verbose_name='Operasyon Adı')),
                ('required_specialty', models.CharField(max_length=100, verbose_name='Gereken Uzmanlık')),
                ('duration_slot', models.PositiveIntegerField(default=1, help_text='Örn: 1 slot = 30 dk, 2 slot = 60 dk', verbose_name='Süre (30dk Slot Sayısı)')),
                ('priority', models.CharField(choices=[('CRITICAL', 'Kritik'), ('HIGH', 'Yüksek'), ('MEDIUM', 'Orta'), ('LOW', 'Düşük')], default='MEDIUM', max_length=10, verbose_name='Öncelik')),
                ('anesthesia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anesthesia.anesthesiateam', verbose_name='Atanan Anestezi')),
                ('required_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.operatingroom', verbose_name='Zorunlu Ameliyathane')),
                ('surgeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surgeon.surgeon', verbose_name='Atanan Cerrah')),
            ],
            options={
                'verbose_name': 'Hasta Ameliyat Operasyonu',
                'verbose_name_plural': 'Hasta Ameliyat Operasyonları',
            },
        ),
    ]
