# Generated by Django 5.2.16 on 2026-08-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_operation', '0002_patientoperation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientoperation',
            name='is_scheduled',
            field=models.BooleanField(default=False, verbose_name='Planlandı mı?'),
        ),
    ]
