# Generated by Django 5.2.16 on 2026-08-13 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_operation', '0003_patientoperation_is_scheduled'),
        ('room', '0002_operatingroom_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientoperation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_operations', to='room.operatingroom'),
        ),
        migrations.AddField(
            model_name='patientoperation',
            name='start_slot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientoperation',
            name='required_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_operations', to='room.operatingroom', verbose_name='Zorunlu Ameliyathane'),
        ),
    ]
